name: toyota_mlflow_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow==2.15.1
      - scikit-learn==1.5.1
      - xgboost==2.1.0
      - pandas==2.2.2
      - numpy==1.26.4
      - matplotlib==3.9.0
      - seaborn==0.13.2
      - cloudpickle==3.0.0
