name: toyota_mlflow_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==3.6.0
      - scikit-learn==1.5.1
      - xgboost==3.1.2
      - pandas==2.2.2
      - numpy==1.26.4
      - matplotlib==3.9.0
      - seaborn==0.13.2
      - cloudpickle==3.0.0
