artifact_location: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/models/m-f35c63a953af40248a826e8ff3eb7d70/artifacts
creation_timestamp: 1765913338190
experiment_id: '0'
last_updated_timestamp: 1765913340207
model_id: m-f35c63a953af40248a826e8ff3eb7d70
model_type: null
name: model
source_run_id: f411d72a8f1d4783a42809b8463631c0
status: 2
status_message: null
