artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/7d5d12f621044cf0ac435df92c71230e/artifacts
end_time: 1765912179188
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7d5d12f621044cf0ac435df92c71230e
run_name: fearless-loon-298
source_name: ''
source_type: 4
source_version: ''
start_time: 1765912175728
status: 3
tags: []
user_id: runner
