artifact_location: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/models/m-b647461b687c43cda949b68bd7930bd3/artifacts
creation_timestamp: 1765906706274
experiment_id: '0'
last_updated_timestamp: 1765906708262
model_id: m-b647461b687c43cda949b68bd7930bd3
model_type: null
name: model
source_run_id: 56e35df8401c4b6d98e5457e7e35c574
status: 2
status_message: null
