artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/bcd7fea0e67b4bb591f3fbf0d2598faf/artifacts
end_time: 1765908098730
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bcd7fea0e67b4bb591f3fbf0d2598faf
run_name: bright-perch-390
source_name: ''
source_type: 4
source_version: ''
start_time: 1765908095009
status: 3
tags: []
user_id: runner
