artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/c85e007e72254e1ea1244903da0601ef/artifacts
end_time: 1765907583179
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c85e007e72254e1ea1244903da0601ef
run_name: charming-swan-794
source_name: ''
source_type: 4
source_version: ''
start_time: 1765907579608
status: 3
tags: []
user_id: runner
