artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/09753a04db2d491daa15ef69af4a5aa8/artifacts
end_time: 1765909284549
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 09753a04db2d491daa15ef69af4a5aa8
run_name: chill-deer-316
source_name: ''
source_type: 4
source_version: ''
start_time: 1765909280939
status: 3
tags: []
user_id: runner
