artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/56e35df8401c4b6d98e5457e7e35c574/artifacts
end_time: 1765906708472
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 56e35df8401c4b6d98e5457e7e35c574
run_name: rumbling-ray-340
source_name: ''
source_type: 4
source_version: ''
start_time: 1765906704958
status: 3
tags: []
user_id: runner
