artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/e1c33d3d058e420080b09d22b2bf6a41/artifacts
end_time: 1765908491937
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e1c33d3d058e420080b09d22b2bf6a41
run_name: likeable-mole-60
source_name: ''
source_type: 4
source_version: ''
start_time: 1765908488305
status: 3
tags: []
user_id: runner
