artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/f411d72a8f1d4783a42809b8463631c0/artifacts
end_time: 1765913340437
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f411d72a8f1d4783a42809b8463631c0
run_name: dazzling-shrimp-482
source_name: ''
source_type: 4
source_version: ''
start_time: 1765913336851
status: 3
tags: []
user_id: runner
