artifact_location: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/models/m-23ad621eb5b24b5d87f1a5bc4416e921/artifacts
creation_timestamp: 1765907580909
experiment_id: '0'
last_updated_timestamp: 1765907582900
model_id: m-23ad621eb5b24b5d87f1a5bc4416e921
model_type: null
name: model
source_run_id: c85e007e72254e1ea1244903da0601ef
status: 2
status_message: null
