artifact_location: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/models/m-8b5dda43dfd34db4baf77055f5d9de51/artifacts
creation_timestamp: 1765908096382
experiment_id: '0'
last_updated_timestamp: 1765908098479
model_id: m-8b5dda43dfd34db4baf77055f5d9de51
model_type: null
name: model
source_run_id: bcd7fea0e67b4bb591f3fbf0d2598faf
status: 2
status_message: null
