artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/5b1896edfcb340ebaf7bcaac5d6b5673/artifacts
end_time: 1765908956430
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5b1896edfcb340ebaf7bcaac5d6b5673
run_name: capable-trout-833
source_name: ''
source_type: 4
source_version: ''
start_time: 1765908952985
status: 3
tags: []
user_id: runner
