artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/c2c3ce209aac4231a67b6ae8c77bdba9/artifacts
end_time: 1765905889901
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c2c3ce209aac4231a67b6ae8c77bdba9
run_name: abundant-hen-439
source_name: ''
source_type: 4
source_version: ''
start_time: 1765905886287
status: 3
tags: []
user_id: runner
